# Generated by Django 5.0.6 on 2024-06-05 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('mini_descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('mas_vendido', models.BooleanField(default=False)),
                ('mejor_valorado', models.BooleanField(default=False)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensiones', models.CharField(max_length=100)),
                ('tallas', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categorias')),
                ('imagenes', models.ManyToManyField(blank=True, to='productos.productosimagenes')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
