# Generated by Django 5.0.6 on 2024-05-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='updated_at',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='created_at',
            new_name='creado',
        ),
    ]
