# Generated by Django 5.0.6 on 2024-05-12 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_rename_updated_at_categorias_actualizado_and_more'),
        ('productos', '0002_rename_updated_at_productos_actualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorias.categorias'),
            preserve_default=False,
        ),
    ]
