# Generated by Django 5.0.6 on 2024-05-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumidores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumidores',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='consumidores',
            name='ciudad',
            field=models.CharField(default='lima', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumidores',
            name='direccion',
            field=models.CharField(default='dsikjd ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumidores',
            name='pais',
            field=models.CharField(default='peru', max_length=50),
            preserve_default=False,
        ),
    ]
