# Generated by Django 5.0.6 on 2024-05-08 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumidores', '0002_remove_consumidores_fecha_nacimiento_and_more'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumidores.consumidores')),
                ('productos', models.ManyToManyField(to='productos.productos')),
            ],
        ),
    ]
