# Generated by Django 5.0.6 on 2024-05-08 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AddField(
            model_name='orden',
            name='desuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='descuentos.descuentos'),
        ),
    ]
