# Generated by Django 5.0.6 on 2024-05-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_orden_options_orden_desuento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='desuento',
            new_name='descuento',
        ),
    ]
