# Generated by Django 5.0.6 on 2024-06-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_orden_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en camino', 'En camino'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
