# Generated by Django 5.0.6 on 2024-05-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_rename_desuento_orden_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en camino', 'En camino'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
